/* Generated By:JavaCC: Do not edit this line. ReaderConstants.java */
package AnalyseSyntaxique;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMICOMMA = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int ORDERBY = 7;
  /** RegularExpression Id. */
  int SELECT = 8;
  /** RegularExpression Id. */
  int UNION = 9;
  /** RegularExpression Id. */
  int ALL = 10;
  /** RegularExpression Id. */
  int FROM = 11;
  /** RegularExpression Id. */
  int WHERE = 12;
  /** RegularExpression Id. */
  int EGAL = 13;
  /** RegularExpression Id. */
  int DIFFERENT = 14;
  /** RegularExpression Id. */
  int INFERIEUR = 15;
  /** RegularExpression Id. */
  int SUPPERIEUR = 16;
  /** RegularExpression Id. */
  int SUPEGAL = 17;
  /** RegularExpression Id. */
  int INFEGAL = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int ENTIER = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int NOM = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\",\"",
    "\"order by\"",
    "\"select\"",
    "\"union\"",
    "\"*\"",
    "\"from\"",
    "\"where\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "<DIGIT>",
    "<ENTIER>",
    "<LETTER>",
    "<NOM>",
  };

}
